---
total_years: 5
number_of_people: 30000
number_of_simulations: 6
social_connectivity: 0.7
subculture_connectivity: 0.5
neighbourhood_connectivity: 0.3
number_of_social_network_links: 5
number_of_neighbour_links: 10
days_in_habit_average: 10
distributions:
  - 
    - 9845.09054289
    - 3691.81319473
    - 0.66987177
  -
    - 2205.44681457
    - 1414.37536528
    - 0.25230344
  -
    - 22606.84196648
    - 11965.0218091
    - 0.07782479